# Generated by Django 4.2.28 on 2026-02-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = []
