# Generated by Django 4.2.28 on 2026-03-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("SuperAdmin", "SuperAdmin"),
                    ("Admin", "Admin"),
                    ("User", "User"),
                ],
                default="User",
                max_length=20,
            ),
        ),
    ]
