# Generated by Django 4.2.28 on 2026-04-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommrece", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stock",
            new_name="quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_available",
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name="product",
            table="api_product",
        ),
    ]
