# Generated by Django 4.2.28 on 2026-03-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
